### ISSUE TITLE
有关bst文件对不同来源文献的格式支持

### ISSUE THREAD

**Issue by Sophie10001b** [cshaowang/swjtuThesisV2.0#2]
在使用模板的过程中，发现目前的bst文件好像没有对网络来源或者arXiv上的引用进行适配，比如在GB/T 7714-2005中对应[EB/OL]的文献。我目前的解决方案是直接套用了misc对应的函数写了一个新的引用格式，并且在里面额外添加了[EB/OL]。不知道作者目前是否方便在bst文件里面引入更多的文献格式适配？

**Comment by cshaowang** [comment]
Fixed. See './ref/swjtuBST.bst'. Thanks.
